name: Frontend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: '3.12'
          cache: true
      - name: Install dependencies
        run: pdm install -Gtest
      - name: Run tests
        run: pdm run pytest
